[package]
name = "intern"
version = "0.1.0"
edition = "2021"
description = "Awesome hash finder!"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.24", features = ["cargo"] }
sha256 = "1.5.0"

[profile.release]
strip = true
lto = true
